script:
  - "npm run travis"

language: node_js

node_js:
  - '4'
  - '6'

branches:
  except:
    - /^v\d+\./

env:
  global:
    - CXX=g++-4.8

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env:
        - TEST_SUITE=test
        - COVERAGE=true
  allow_failures:
    - env:
        - TEST_SUITE=test
        - COVERAGE=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false
